language: python
python:
  - "2.6"
  - "2.7"
  - "nightly"
  - "pypy"
services:
  - mongodb
install:
  - pip install coveralls
script:
  coverage run --source=mongoengine_mls setup.py test
after_success:
  coveralls
